services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=spothero_rates
    ports:
      - '5432:5432'

  barzilai-challenge:
    container_name: barzilai-challenge
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/spothero_rates
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - psql-db