spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spothero_rates
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 5000

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
